const HIGH = 20
const MEDIUM = 15
const LOW = 10
const NONE = 0

export const p = {
  'player-1': {
    id: 'player-1',
    first: {
      damage: HIGH,
      range: 2,
      hit: 1,
      heal: NONE,
      chance: 70,
    },
    second: {
      damage: MEDIUM,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 60,
    },
    third: {
      damage: LOW,
      range: 2,
      hit: 3,
      heal: NONE,
      chance: 50,
    },
    life: 100,
  },
  'player-2': {
    id: 'player-2',
    first: {
      damage: MEDIUM,
      range: 6,
      hit: 1,
      heal: NONE,
      chance: 80,
    },
    second: {
      damage: LOW,
      range: 5,
      hit: 2,
      heal: NONE,
      chance: 70,
    },
    third: {
      damage: NONE,
      range: 8,
      hit: 1,
      heal: HIGH,
      chance: 90,
    },
    life: 100,
  },
  'player-3': {
    id: 'player-3',
    first: {
      damage: MEDIUM,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 60,
    },
    second: {
      damage: LOW,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 80,
    },
    third: {
      damage: MEDIUM,
      range: 4,
      hit: 1,
      heal: NONE,
      chance: 90,
    },
    life: 100,
  },
  'player-4': {
    id: 'player-4',
    first: {
      damage: NONE,
      range: 8,
      hit: 4,
      heal: MEDIUM,
      chance: 80,
    },
    second: {
      damage: LOW,
      range: 6,
      hit: 4,
      heal: NONE,
      chance: 60,
    },
    third: {
      damage: MEDIUM,
      range: 8,
      hit: 2,
      heal: NONE,
      chance: 40,
    },
    life: 100,
  },
  'player-5': {
    id: 'player-5',
    first: {
      damage: HIGH,
      range: 2,
      hit: 1,
      heal: NONE,
      chance: 70,
    },
    second: {
      damage: MEDIUM,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 60,
    },
    third: {
      damage: LOW,
      range: 2,
      hit: 3,
      heal: NONE,
      chance: 50,
    },
    life: 100,
  },
  'player-6': {
    id: 'player-6',
    first: {
      damage: MEDIUM,
      range: 6,
      hit: 1,
      heal: NONE,
      chance: 80,
    },
    second: {
      damage: LOW,
      range: 5,
      hit: 2,
      heal: NONE,
      chance: 70,
    },
    third: {
      damage: NONE,
      range: 8,
      hit: 1,
      heal: HIGH,
      chance: 90,
    },
    life: 100,
  },
  'player-7': {
    id: 'player-7',
    first: {
      damage: MEDIUM,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 60,
    },
    second: {
      damage: LOW,
      range: 2,
      hit: 2,
      heal: NONE,
      chance: 80,
    },
    third: {
      damage: MEDIUM,
      range: 4,
      hit: 1,
      heal: NONE,
      chance: 90,
    },
    life: 100,
  },
  'player-8': {
    id: 'player-8',
    first: {
      damage: NONE,
      range: 8,
      hit: 4,
      heal: MEDIUM,
      chance: 80,
    },
    second: {
      damage: LOW,
      range: 6,
      hit: 4,
      heal: NONE,
      chance: 60,
    },
    third: {
      damage: MEDIUM,
      range: 8,
      hit: 2,
      heal: NONE,
      chance: 40,
    },
    life: 100,
  },
}